name: GTN downloader

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 30 23 * * 6 # minute hour month-day month week-day

jobs:
  execute_script:
    runs-on: ubuntu-latest

    env:
      ONECLIENT_ACCESS_TOKEN: ${{ secrets.ONECLIENT_ACCESS_TOKEN }}
      ONECLIENT_PROVIDER_HOST: ${{ secrets.ONECLIENT_PROVIDER_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone the training-material repo
        run: |
          git clone --depth 1 https://github.com/galaxyproject/training-material.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run oneclient in Docker
        run: |
          docker run --rm --privileged \
            -e ONECLIENT_ACCESS_TOKEN=${ONECLIENT_ACCESS_TOKEN} \
            -e ONECLIENT_PROVIDER_HOST=${ONECLIENT_PROVIDER_HOST} \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            onedata/oneclient:21.02.1 \
            bash -c "
              apt-get update && apt-get install -y python3-pip && \
              pip install -r requirements.txt && \
              python bin/data-library-download.py \
                --input training-material \
                --output /mnt/onedata/GTN\ data
            "
