name: GTN downloader - test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gtn-download:
    runs-on: ubuntu-latest
    env:
      ONECLIENT_ACCESS_TOKEN: ${{ secrets.ONECLIENT_ACCESS_TOKEN }}
      ONECLIENT_PROVIDER_HOST: ${{ secrets.ONECLIENT_PROVIDER_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone training-material repo
        run: git clone --depth 1 https://github.com/galaxyproject/training-material.git

      - name: Run GTN-downloader in Docker
        run: |
          docker run --rm --privileged \
            --entrypoint bash \
            -e ONECLIENT_ACCESS_TOKEN=${ONECLIENT_ACCESS_TOKEN} \
            -e ONECLIENT_PROVIDER_HOST=${ONECLIENT_PROVIDER_HOST} \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            onedata/oneclient:21.02.1 -c "
              set -e
              mkdir -p /mnt/onedata
              oneclient /mnt/onedata &
              sleep 5
              apt-get update && apt-get install -y python3 python3-pip
              pip3 install -r requirements.txt
              python3 bin/download_from_tsv.py'
            "