name: GTN downloader - test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 30 23 * * 6 # minute hour month-day month week-day

jobs:
  gtn-download:
    runs-on: ubuntu-latest
    env:
      ONECLIENT_ACCESS_TOKEN: ${{ secrets.ONECLIENT_ACCESS_TOKEN }}
      ONECLIENT_PROVIDER_HOST: ${{ secrets.ONECLIENT_PROVIDER_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone training-material repo
        run: git clone --depth 1 https://github.com/galaxyproject/training-material.git

      - name: Build skip list of existing files in Onedata
        run: |
          docker run --rm --privileged \
            -e ONECLIENT_ACCESS_TOKEN=${ONECLIENT_ACCESS_TOKEN} \
            -e ONECLIENT_PROVIDER_HOST=${ONECLIENT_PROVIDER_HOST} \
            -v ${{ github.workspace }}:/workspace \
            onedata/oneclient:21.02.1 bash -c "
              mkdir -p /mnt/onedata
              oneclient /mnt/onedata
              sleep 5
              find '/mnt/onedata/GTN data' -type f -printf '%P\n' > /workspace/existing.txt || true
            "

      - name: Run GTN downloader
        run: |
          python3 -m pip install -r requirements.txt
          python3 bin/test-download.py \
            --input training-material \
            --skip-list existing.txt

      - name: Push local cache to Onedata
        run: |
          docker run --rm --privileged \
            -e ONECLIENT_ACCESS_TOKEN=${ONECLIENT_ACCESS_TOKEN} \
            -e ONECLIENT_PROVIDER_HOST=${ONECLIENT_PROVIDER_HOST} \
            -v ${{ github.workspace }}:/workspace \
            onedata/oneclient:21.02.1 bash -c "
              mkdir -p /mnt/onedata
              oneclient /mnt/onedata
              sleep 5
              apt-get update && apt-get install -y rsync
              rsync -av --progress /workspace/cache/ '/mnt/onedata/GTN data/'
            "

      - name: Upload summary file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-summary
          path: tmp/download-summary.tsv